### ISSUE TITLE
[cant load in PC] 1.12.2

### ISSUE THREAD

**Issue by hasezoey** [mrmakeit/OCJS#17] opened 2017-12-19 20:17 UTC
"failed loading bios: bios:1: syntax error near 'dec2string'" - i think it trys to execute as lua
+ i cant find the "JS" CPU, only the JS-EEPRom (i think thats why)

do i something wrong?

OCJS Version: 0.5.1 (Curse/Twitch Version)
OpenComputers Version: 1.7.1.43 (^)
Forge Version: 14.23.1.2573

**Comment by mrmakeit** [comment] 2017-12-21 17:09
The architecture is part of the cpu provided by OpenComputers.  You'll need to sneak-rightclick with the cpu in your hand to change it.

**Comment by mrmakeit** [comment] 2017-12-21 17:25
Duplicate of #14

**Closed by mrmakeit** 2017-12-21 17:25 UTC
